[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"

# Live Stripe and App URLs are placeholders and should be set in Netlify UI
  NEXT_PUBLIC_APP_URL = "https://graceful-crisp-e96a53.netlify.app"
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "pk_live_YOUR_STRIPE_PUBLISHABLE_KEY"
  STRIPE_SECRET_KEY = "sk_live_YOUR_STRIPE_SECRET_KEY"
  STRIPE_WEBHOOK_SECRET = "whsec_YOUR_STRIPE_WEBHOOK_SECRET"

[[plugins]]
  package = "@netlify/plugin-nextjs"
