name: 🐛 Bug Report
description: Report a bug or issue with the Berenice London platform
title: "🐛 [Bug]: "
labels: ["bug", "needs-triage"]
assignees:
  - berenicelondon
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out this form as completely as possible.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following before submitting
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I have tried to reproduce this issue in an incognito/private browser window
          required: true
        - label: I have cleared my browser cache and cookies
          required: false

  - type: dropdown
    id: bug-type
    attributes:
      label: Bug Type
      description: What type of bug is this?
      options:
        - UI/UX Issue
        - Payment Processing
        - Authentication
        - Performance
        - Security
        - Mobile Responsiveness
        - API/Backend
        - Virtual Try-On
        - Chatbot
        - Admin Panel
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (Site is down/broken)
        - High (Major feature broken)
        - Medium (Feature partially broken)
        - Low (Minor issue)
        - Cosmetic (Visual issue only)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: If applicable, add screenshots or videos to help explain your problem
      placeholder: Drag and drop images/videos here or paste URLs

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Opera
        - Mobile Safari (iOS)
        - Chrome Mobile (Android)
        - Samsung Internet
        - Other
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: Browser Version
      description: What version of the browser are you using?
      placeholder: e.g., Chrome 120.0.6099.62

  - type: dropdown
    id: device
    attributes:
      label: Device Type
      description: What type of device are you using?
      options:
        - Desktop/Laptop
        - Mobile Phone
        - Tablet
        - Other
    validations:
      required: true

  - type: input
    id: device-details
    attributes:
      label: Device Details
      description: Device model and operating system
      placeholder: e.g., iPhone 14 Pro (iOS 17.1), Windows 11, macOS Sonoma

  - type: dropdown
    id: user-type
    attributes:
      label: User Type
      description: What type of user are you?
      options:
        - Guest User
        - Registered User (Basic)
        - Premium Member
        - Elite Member
        - Admin User
    validations:
      required: true

  - type: textarea
    id: error-logs
    attributes:
      label: Error Messages/Console Logs
      description: Any error messages or console logs (open browser developer tools to check)
      placeholder: Paste any error messages or console logs here
      render: shell

  - type: input
    id: url
    attributes:
      label: Page URL
      description: URL where the bug occurred
      placeholder: https://berenicelondon.co.uk/...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might help...

  - type: checkboxes
    id: privacy
    attributes:
      label: Privacy Notice
      description: Please confirm you understand our privacy policy
      options:
        - label: I understand that any information provided may be used for debugging purposes
          required: true
