name: ✨ Feature Request
description: Suggest a new feature or enhancement for the Berenice London platform
title: "✨ [Feature]: "
labels: ["enhancement", "needs-discussion"]
assignees:
  - berenicelondon
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following before submitting
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: I have checked the roadmap to see if this feature is already planned
          required: true
        - label: This is a feature request and not a bug report
          required: true

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: Which area does this feature relate to?
      options:
        - E-commerce Core
        - Payment System
        - User Authentication
        - Virtual Try-On
        - AI Chatbot
        - Admin Panel
        - Mobile Experience
        - Performance
        - SEO/Marketing
        - Security
        - Analytics
        - API
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Critical (Business critical)
        - High (Very important)
        - Medium (Nice to have)
        - Low (Future consideration)
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What pain point are you experiencing?
      placeholder: Describe the problem this feature would solve...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternative solutions you've considered...

  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: Write a user story for this feature
      placeholder: "As a [type of user], I want [feature] so that [benefit/goal]..."
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: Target User Type
      description: Which users would benefit from this feature?
      multiple: true
      options:
        - All Users
        - Guest Users
        - Registered Users
        - Premium Members
        - Elite Members
        - Admin Users
        - Mobile Users
        - Desktop Users
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What criteria must be met for this feature to be considered complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Wireframes
      description: If you have any mockups, wireframes, or visual examples, please share them
      placeholder: Drag and drop images here or paste URLs

  - type: dropdown
    id: implementation-complexity
    attributes:
      label: Expected Implementation Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple (Few hours)
        - Medium (Few days)
        - Complex (Few weeks)
        - Very Complex (Months)
        - Not sure
    validations:
      required: true

  - type: textarea
    id: business-impact
    attributes:
      label: Business Impact
      description: How would this feature impact the business or user experience?
      placeholder: Describe the potential business impact...

  - type: checkboxes
    id: technical-considerations
    attributes:
      label: Technical Considerations
      description: Are there any technical considerations for this feature?
      options:
        - label: This feature may require database changes
        - label: This feature may require API changes
        - label: This feature may impact performance
        - label: This feature may require third-party integrations
        - label: This feature may have security implications
        - label: This feature may affect mobile experience
        - label: This feature may require design system updates

  - type: textarea
    id: related-features
    attributes:
      label: Related Features/Issues
      description: Are there any related features or existing issues?
      placeholder: Link to related issues or describe related features...

  - type: dropdown
    id: urgency
    attributes:
      label: Timeline/Urgency
      description: When would you like to see this feature implemented?
      options:
        - ASAP (Critical for business)
        - Next release cycle
        - Within 3 months
        - Within 6 months
        - Future roadmap
        - No specific timeline
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any additional context, screenshots, or information
      placeholder: Add any other context about the feature request here...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in contributing to this feature?
      options:
        - label: I would be willing to help implement this feature
        - label: I would be willing to help test this feature
        - label: I would be willing to help with documentation
        - label: I would be willing to provide feedback during development
