[build]
  command = "npm run build"
  # For Next.js with server features, don't specify publish directory
  # Let the Next.js plugin handle it

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  # Enable legacy peer deps to handle dependency conflicts
  NPM_FLAGS = "--legacy-peer-deps"
  # Disable telemetry for faster builds
  NEXT_TELEMETRY_DISABLED = "1"
  # Set production environment
  NODE_ENV = "production"

# Use Netlify's Next.js plugin for full SSR support
[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "npm run dev"
  port = 3000

# Handle image optimization
[images]
  remote_images = [
    "https://source.unsplash.com/.*",
    "https://images.unsplash.com/.*",
    "https://ext.same-assets.com/.*",
    "https://ugc.same-assets.com/.*"
  ]

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# API routes headers
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Static assets caching
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
